### ISSUE TITLE
Support for LineageOS Themes / Styles

### ISSUE THREAD

**Issue by famo** [SimpleMobileTools/Simple-App-Launcher#114] opened 2021-01-28 20:45 UTC
LineageOS provides a Style API, see: https://wiki.lineageos.org/sdk/api/styles.html
If your SimpleMobileTools would make use of this API, your apps could change background color and app icon color according to system color. This would make you apps look really good out of the box and would make them really attractive on lineageOS!

Thanks for considering.

PS:
Issue actually belongs to https://github.com/SimpleMobileTools/Simple-Commons/, but for some reason I can't open issues there.

**Comment by tibbi** [comment] 2021-01-28 22:04
just as written in Simple Commons, issues related to all apps belong to General Discussion. Duplicate of https://github.com/SimpleMobileTools/General-Discussion/issues/135

**Closed by tibbi** 2021-01-28 22:04 UTC
