### ISSUE TITLE
Add option to remove app drawer

### ISSUE THREAD

**Issue by Rexadev** [SimpleMobileTools/Simple-App-Launcher#180] opened 2022-10-17 19:32 UTC
and have all apps on home screen.

**Comment by tibbi** [comment] 2022-10-17 20:21
this app is just a basic icon wrapper, guess you mean Simple Launcher. Duplicate of https://github.com/SimpleMobileTools/Simple-Launcher/issues/22

**Closed by tibbi** 2022-10-17 20:21 UTC
